### ISSUE TITLE
🐛 PyPI: `Can't have direct dependency`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/cpac#45]
### Describe the bug

> ### Direct URL dependencies
> ⚠️ Attention
> 
> [PyPI](https://pypi.org/) and other standards-conformant package indices **do not** accept packages that declare dependencies using direct URLs. `pip` will accept them when installing packages from the local filesystem or from another URL, however.

― [Dependencies Management in Setuptools: Direct URL dependencies](https://setuptools--4096.org.readthedocs.build/en/4096/userguide/dependency_management.html#direct-url-dependencies)

Until [`ba-timeseries-gradients`](https://github.com/cmi-dair/ba-timeseries-gradients) and [`tsconcat`](https://github.com/cmi-dair/tsconcat) publish to PyPI, we can't publish with them as dependencies

### Expected behavior

`cpac` updates can be published to PyPI

### Acceptance criteria

Either 
- [x] both of these new dependencies get published to PyPI or are containerized,
   - [x] `ba-timeseries-gradients`
     - [ ] https://github.com/cmi-dair/ba-timeseries-gradients/issues/14
     - [x] [`ghcr.io/cmi-dair/ba-timeseries-gradients:main`](https://github.com/childmindresearch/ba-timeseries-gradients/pkgs/container/ba-timeseries-gradients)
   - [x] `ba-tsconcat`
     - [x] [`ba-tsconcat` published on PyPI](https://github.com/cmi-dair/tsconcat/actions/runs/7463248456)
- [x] we install them in the C-PAC container and wrap them via that container with this wrapper,
- [x] we reconsider #39,
- [ ] we pull cpac from PyPI and require users to install from GitHub,
      or
- [ ] we require users to install those dependencies from GitHub if they want to use them

#### with direct URL dependencies

<img width="948" alt="with (failure)" src="https://github.com/FCP-INDI/cpac/assets/5974438/456ec797-3bc5-4059-925a-f489242f606f">

#### without direct URL dependencies

<img width="949" alt="without (success)" src="https://github.com/FCP-INDI/cpac/assets/5974438/70ac7ea9-1b10-416d-80c5-0d7edd3d3a73">

### Additional context

* [PyPI Doesn't Allow Git Repo Dependencies](https://til.dchan.cc/posts/11-29-2022/)

**Comment by nx10** [comment]
@ReinderVosDeWael let's just release these on pypi to make this easy. Maybe we can also use this to standardize a release action for https://github.com/cmi-dair/template-python-repository/issues/85

**Comment by nx10** [comment]
Released tsconcat https://pypi.org/project/ba-tsconcat/
